window.E2E_SEED = [
  {
    id: 'aabybropizza',
    name: "Aabybro's Pizza & Steak House",
    address: '9440 Aabybro',
    city: 'Aabybro',
    lat: 57.162,
    lng: 9.74,
    phone: '98279100',
    website: 'https://www.aabybropizza.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'adamspizza',
    name: 'Adams Pizzaria Skødstrup',
    address: 'Grenåvej 787, 8541 Skødstrup',
    city: 'Skødstrup',
    lat: 56.262,
    lng: 10.31,
    phone: '86993594',
    website: 'https://www.adamspizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'alaturka',
    name: 'Alaturka Restaurant i Grindsted',
    address: 'Fynsgade 13A, 7200 Grindsted',
    city: 'Grindsted',
    lat: 55.754,
    lng: 8.927,
    phone: '60567533',
    website: 'https://www.alaturka.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'alcaponepizza',
    name: 'Al Capone Pizza i Esbjerg',
    address: 'Frodesgade 111 6700 Esbjerg',
    city: 'Esbjerg',
    lat: 55.467,
    lng: 8.452,
    phone: '75141420',
    website: 'https://www.alcaponepizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'alibabas-pizza',
    name: 'Ali Babas Pizza & Grill i Vamdrup',
    address: 'Vestergade 30, 6580 Vamdrup',
    city: 'Vamdrup',
    lat: 55.428,
    lng: 9.478,
    phone: '75581515',
    website: 'https://www.alibabas-pizza.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'almindpizza',
    name: 'Jacob Almind Pizza & Grill i Almind',
    address: '6051 Almind',
    city: 'Almind',
    lat: 55.557,
    lng: 9.488,
    phone: '75561777',
    website: 'https://www.almindpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'alrayespizza',
    name: 'Al Rayes Pizza & manakish i Aarhus, Inger Christensens ',
    address: '8220 Brabrand',
    city: 'Brabrand',
    lat: 56.153,
    lng: 10.135,
    phone: '50235029',
    website: 'https://www.alrayespizza.dk',
    hoursOpen: '09:00',
    hoursClose: '20:30',
    delivery: true,
    active: true
  },
  {
    id: 'alsgadepizza',
    name: 'Alsgade Pizza & Grill Take Away Menu i Sønderborg',
    address: 'Alsgade 76, 6400 Sønderborg',
    city: 'Sønderborg',
    lat: 54.909,
    lng: 9.792,
    phone: '74432223',
    website: 'https://www.alsgadepizza.dk',
    hoursOpen: '10:30',
    hoursClose: '22:00',
    delivery: true,
    active: true
  },
  {
    id: 'amigopizza',
    name: 'Amigo Pizzeria',
    address: 'Mommarkvej 264, 6470 Sydals',
    city: 'Sydals',
    lat: 54.899,
    lng: 10.042,
    phone: '74407714',
    website: 'https://www.amigopizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'amigosvodskov',
    name: 'Amigos Pizza',
    address: 'Vodskovvej 25E, 9310 Vodskov',
    city: 'Vodskov',
    lat: 57.109,
    lng: 10.022,
    phone: '98291370',
    website: 'https://www.amigosvodskov.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'amore-pizza',
    name: 'Kebab Huset Amore',
    address: 'Thomsensgade 2 B, 7800 Skive',
    city: 'Skive',
    lat: 56.567,
    lng: 9.027,
    phone: '97524318',
    website: 'https://www.amore-pizza.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'amorpizza',
    name: 'Amor Pizza Aalborg l',
    address: 'Stationsvej 31, 9400 Nørresundby',
    city: 'Nørresundby',
    lat: 57.059,
    lng: 9.922,
    phone: '98194555',
    website: 'https://www.amorpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'anaskebab',
    name: 'Anas Kebab Roskilde',
    address: 'Helligkorsvej 12, 4000 Roskilde',
    city: 'Roskilde',
    lat: 55.642,
    lng: 12.08,
    phone: '91192171',
    website: 'https://www.anaskebab.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'andospizza',
    name: 'Andos Pizza i Aalborg',
    address: 'Søndergade 43, 9000 Aalborg',
    city: 'Aalborg',
    lat: 57.048,
    lng: 9.922,
    phone: '98162016',
    website: 'https://www.andospizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'arizonapizza',
    name: 'Arizona Pizza Esbjerg',
    address: 'Isbjørnevej 132, 6715 Esbjerg N',
    city: 'Esbjerg N',
    lat: 55.521,
    lng: 8.469,
    phone: '75757272',
    website: 'https://www.arizonapizza.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'augustenborg-pizza',
    name: 'Augustenborg Pizza & Grill',
    address: 'Centervej 2, 6440 Augustenborg',
    city: 'Augustenborg',
    lat: 54.944,
    lng: 9.872,
    phone: '73702540',
    website: 'https://www.augustenborg-pizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'babaspizza',
    name: 'Babas Pizza & Grill i Esbjerg',
    address: '1823',
    city: 'Forsiden',
    lat: 56.26,
    lng: 9.5,
    phone: '93921823',
    website: 'https://www.babaspizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'bambi-pizza',
    name: 'Bambi Pizza og Grill House Holstebro',
    address: 'Struervej 49, 7500 Holstebro',
    city: 'Holstebro',
    lat: 56.36,
    lng: 8.62,
    phone: '97425125',
    website: 'https://www.bambi-pizza.dk',
    hoursOpen: '12:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'bellaitalia',
    name: 'Bella Italia Pizza Esbjerg',
    address: 'Vardevej 171, 6715 Esbjerg',
    city: 'Esbjerg',
    lat: 55.521,
    lng: 8.469,
    phone: '75459001',
    website: 'https://www.bellaitalia.dk',
    hoursOpen: '14:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'bellavodskov',
    name: 'Bella Italia Pizza og Grill I Vodskov',
    address: 'Vodskovvej 35, 9310 Vodskov',
    city: 'Vodskov',
    lat: 57.109,
    lng: 10.022,
    phone: '52705877',
    website: 'https://www.bellavodskov.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'bigbite',
    name: 'Big Bite Pizza & Burger',
    address: 'Fyensgade 38, 9000 Aalborg',
    city: 'Aalborg',
    lat: 57.048,
    lng: 9.922,
    phone: '98102079',
    website: 'https://www.bigbite.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'bogeskovpizza',
    name: 'Bøgeskov Pizza og Steakhouse i Bøgeskov, Fredericia',
    address: 'Bøgeskovvej 41, 7000 Fredericia',
    city: 'Fredericia',
    lat: 56.26,
    lng: 9.5,
    phone: '75727072',
    website: 'https://www.bogeskovpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'brammingpizza',
    name: 'Bramming Pizza og Kebabhouse',
    address: 'Nørregade 25, 6740 Bramming',
    city: 'Bramming',
    lat: 55.469,
    lng: 8.703,
    phone: '75174700',
    website: 'https://www.brammingpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'broagerpizza',
    name: 'Broager Pizza I Broager',
    address: 'Storegade 23 6310 Broager',
    city: 'Broager',
    lat: 54.891,
    lng: 9.672,
    phone: '73441312',
    website: 'https://www.broagerpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'byenspizzaria',
    name: 'Byens Pizzaria',
    address: 'Nørregade 10, 9700 Brønderslev',
    city: 'Brønderslev',
    lat: 56.26,
    lng: 9.5,
    phone: '98802024',
    website: 'https://www.byenspizzaria.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'cafealfa',
    name: 'Cafe Alfa Holstebro',
    address: 'Nørregade 48, 7500 Holstebro',
    city: 'Holstebro',
    lat: 56.36,
    lng: 8.62,
    phone: '81864929',
    website: 'https://www.cafealfa.dk',
    hoursOpen: '11:00',
    hoursClose: '20:00',
    delivery: true,
    active: true
  },
  {
    id: 'cafeistanbul',
    name: 'Cafe Istanbul Pizza Haderslev',
    address: 'Apotekergade 2 st. 6100 Haderslev',
    city: 'Haderslev',
    lat: 56.26,
    lng: 9.5,
    phone: '73531095',
    website: 'https://www.cafeistanbul.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'centrepalace',
    name: 'Centre Palace',
    address: '2078',
    city: 'Forsiden',
    lat: 56.26,
    lng: 9.5,
    phone: '86102078',
    website: 'https://www.centrepalace.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'chaps-pizza',
    name: 'Chaps Pizza i Aabenraa',
    address: 'Vestergade 7A, 6200 Åbenrå',
    city: 'Åbenrå',
    lat: 55.044,
    lng: 9.418,
    phone: '73622200',
    website: 'https://www.chaps-pizza.dk',
    hoursOpen: '16:00',
    hoursClose: '20:45',
    delivery: true,
    active: true
  },
  {
    id: 'dannipizzaoggrill',
    name: 'Danni Pizza & Grill i Aarhus',
    address: 'Larsensvej 4, 8220 Brabrand',
    city: 'Brabrand',
    lat: 56.153,
    lng: 10.135,
    phone: '86614412',
    website: 'https://www.dannipizzaoggrill.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'davinciaulum',
    name: 'Da Vinci Aulum',
    address: 'Danmarksgade 3-5, 7490 Aulum',
    city: 'Aulum',
    lat: 56.266,
    lng: 8.789,
    phone: '97427490',
    website: 'https://www.davinciaulum.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'dinospizza',
    name: 'Dinos Pizza & Restaurant i Struer',
    address: 'Østergade 34 7600 Struer',
    city: 'Struer',
    lat: 56.484,
    lng: 8.594,
    phone: '97852525',
    website: 'https://www.dinospizza.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'dinosroslev',
    name: "Dino's Pizzaria i Roslev",
    address: 'Frederiksgade 17, 7870 Roslev',
    city: 'Roslev',
    lat: 56.7,
    lng: 8.982,
    phone: '97591533',
    website: 'https://www.dinosroslev.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'doropizza',
    name: 'Doro Pizza Restaurant i Gråsten',
    address: '6800',
    city: 'Forsiden',
    lat: 56.26,
    lng: 9.5,
    phone: '74654240',
    website: 'https://www.doropizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'emmapizza',
    name: 'Emma Pizza & Grill i Aarhus',
    address: 'Sønderborggade 9, 8000 Aarhus',
    city: 'Aarhus',
    lat: 56.157,
    lng: 10.203,
    phone: '86144949',
    website: 'https://www.emmapizza.dk',
    hoursOpen: '15:30',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'falafelhouse',
    name: 'Falafel House i Aalborg',
    address: 'Reberbansgade 16 A, 9000 Aalborg',
    city: 'Aalborg',
    lat: 57.048,
    lng: 9.922,
    phone: '32117311',
    website: 'https://www.falafelhouse.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'fanoepizza',
    name: 'Fanø Pizza på Fanø',
    address: 'Valdemarsvej 14, 6720 Fanø',
    city: 'Fanø',
    lat: 55.416,
    lng: 8.407,
    phone: '75161122',
    website: 'https://www.fanoepizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'gedvedgrillen',
    name: 'Gedved Grillen i Gedved',
    address: 'Egebjergvej 21, 8751 Gedved',
    city: 'Gedved',
    lat: 55.932,
    lng: 9.847,
    phone: '30113444',
    website: 'https://www.gedvedgrillen.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'goldenspizza',
    name: 'Goldens Pizza og Burger i Børkop',
    address: '1555',
    city: 'Forsiden',
    lat: 56.26,
    lng: 9.5,
    phone: '75861555',
    website: 'https://www.goldenspizza.dk',
    hoursOpen: '12:00',
    hoursClose: '21:30',
    delivery: true,
    active: true
  },
  {
    id: 'gustoherning',
    name: 'Gusto Sandwich & Pizza Herning',
    address: 'Østergade 12, 7400 Herning',
    city: 'Herning',
    lat: 56.139,
    lng: 8.974,
    phone: '71662090',
    website: 'https://www.gustoherning.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'pizza-mix',
    name: 'Velkommen til Pizza Mix i Aalborg! Vi tilbyder et stort',
    address: 'Danmarksgade 28, 9000 Aalborg',
    city: 'Aalborg',
    lat: 57.048,
    lng: 9.922,
    phone: '98160316',
    website: 'https://www.pizza-mix.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'r-pizza',
    name: 'Rønhaveplads Pizza & Grill Sønderborg. Byens bedste Tak',
    address: 'Rønhaveplads 7 6400 Sønderborg',
    city: 'Sønderborg',
    lat: 54.909,
    lng: 9.792,
    phone: '74436446',
    website: 'https://www.r-pizza.dk',
    hoursOpen: '10:45',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'sakurasushibar',
    name: 'Sakura Sushi Bar i Horsens',
    address: '2288',
    city: 'Forsiden',
    lat: 56.26,
    lng: 9.5,
    phone: '29792288',
    website: 'https://www.sakurasushibar.dk',
    hoursOpen: '14:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'skalborgpizza',
    name: 'Skalborg Pizza',
    address: 'Hobrovej 390, 9200 Aalborg SV',
    city: 'Aalborg SV',
    lat: 57.014,
    lng: 9.901,
    phone: '98182327',
    website: 'https://www.skalborgpizza.dk',
    hoursOpen: '16:00',
    hoursClose: '20:25',
    delivery: true,
    active: true
  }
];
