window.E2E_SEED = [
  {
    id: 'aabybropizza',
    name: "Aabybro's Pizza & Steak House",
    street: 'Torvet 3',
    zip: '9440',
    address: 'Torvet 3, 9440 Aabybro',
    city: 'Aabybro',
    lat: 57.162,
    lng: 9.74,
    phone: '98279100',
    website: 'https://www.aabybropizza.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'adamspizza',
    name: 'Adams Pizzaria Skødstrup',
    street: 'Grenåvej 787',
    zip: '8541',
    address: 'Grenåvej 787, 8541 Skødstrup',
    city: 'Skødstrup',
    lat: 56.262,
    lng: 10.31,
    phone: '86993594',
    website: 'https://www.adamspizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'alaturka',
    name: 'Alaturka Restaurant i Grindsted',
    street: 'Fynsgade 13A',
    zip: '7200',
    address: 'Fynsgade 13A, 7200 Grindsted',
    city: 'Grindsted',
    lat: 55.754,
    lng: 8.927,
    phone: '60567533',
    website: 'https://www.alaturka.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'alcaponepizza',
    name: 'Al Capone Pizza i Esbjerg',
    street: 'Frodesgade 111',
    zip: '6700',
    address: 'Frodesgade 111, 6700 Esbjerg',
    city: 'Esbjerg',
    lat: 55.467,
    lng: 8.452,
    phone: '75141420',
    website: 'https://www.alcaponepizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'alibabas-pizza',
    name: 'Ali Babas Pizza & Grill i Vamdrup',
    street: 'Vestergade 30',
    zip: '6580',
    address: 'Vestergade 30, 6580 Vamdrup',
    city: 'Vamdrup',
    lat: 55.428,
    lng: 9.478,
    phone: '75581515',
    website: 'https://www.alibabas-pizza.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'almindpizza',
    name: 'Jacob Almind Pizza & Grill i Almind',
    street: 'Almind Kirkesti 2',
    zip: '6051',
    address: 'Almind Kirkesti 2, 6051 Almind',
    city: 'Almind',
    lat: 55.557,
    lng: 9.488,
    phone: '75561777',
    website: 'https://www.almindpizza.dk',
    hoursOpen: '15:30',
    hoursClose: '20:30',
    delivery: true,
    active: true
  },
  {
    id: 'alrayespizza',
    name: 'Al Rayes Pizza & manakish i Aarhus, Inger Christensens ',
    street: '',
    zip: '8220',
    address: '8220 Brabrand',
    city: 'Brabrand',
    lat: 56.153,
    lng: 10.135,
    phone: '50235029',
    website: 'https://www.alrayespizza.dk',
    hoursOpen: '09:00',
    hoursClose: '20:30',
    delivery: true,
    active: true
  },
  {
    id: 'alsgadepizza',
    name: 'Alsgade Pizza & Grill Take Away Menu i Sønderborg',
    street: 'Alsgade 76',
    zip: '6400',
    address: 'Alsgade 76, 6400 Sønderborg',
    city: 'Sønderborg',
    lat: 54.909,
    lng: 9.792,
    phone: '74432223',
    website: 'https://www.alsgadepizza.dk',
    hoursOpen: '10:30',
    hoursClose: '22:00',
    delivery: true,
    active: true
  },
  {
    id: 'amigopizza',
    name: 'Amigo Pizzeria',
    street: 'Mommarkvej 264',
    zip: '6470',
    address: 'Mommarkvej 264, 6470 Sydals',
    city: 'Sydals',
    lat: 54.899,
    lng: 10.042,
    phone: '74407714',
    website: 'https://www.amigopizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'amigosvodskov',
    name: 'Amigos Pizza',
    street: 'Vodskovvej 25E',
    zip: '9310',
    address: 'Vodskovvej 25E, 9310 Vodskov',
    city: 'Vodskov',
    lat: 57.109,
    lng: 10.022,
    phone: '98291370',
    website: 'https://www.amigosvodskov.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'amore-pizza',
    name: 'Kebab Huset Amore',
    street: 'Thomsensgade 2 B',
    zip: '7800',
    address: 'Thomsensgade 2 B, 7800 Skive',
    city: 'Skive',
    lat: 56.567,
    lng: 9.027,
    phone: '97524318',
    website: 'https://www.amore-pizza.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'amorpizza',
    name: 'Amor Pizza Aalborg l',
    street: 'Stationsvej 31',
    zip: '9400',
    address: 'Stationsvej 31, 9400 Nørresundby',
    city: 'Nørresundby',
    lat: 57.059,
    lng: 9.922,
    phone: '98194555',
    website: 'https://www.amorpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'anaskebab',
    name: 'Anas Kebab Roskilde',
    street: 'Helligkorsvej 12',
    zip: '4000',
    address: 'Helligkorsvej 12, 4000 Roskilde',
    city: 'Roskilde',
    lat: 55.642,
    lng: 12.08,
    phone: '91192171',
    website: 'https://www.anaskebab.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'andospizza',
    name: 'Andos Pizza i Aalborg',
    street: 'Søndergade 43',
    zip: '9000',
    address: 'Søndergade 43, 9000 Aalborg',
    city: 'Aalborg',
    lat: 57.048,
    lng: 9.922,
    phone: '98162016',
    website: 'https://www.andospizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'arizonapizza',
    name: 'Arizona Pizza Esbjerg',
    street: 'Isbjørnevej 132',
    zip: '6715',
    address: 'Isbjørnevej 132, 6715 Esbjerg N',
    city: 'Esbjerg N',
    lat: 55.521,
    lng: 8.469,
    phone: '75757272',
    website: 'https://www.arizonapizza.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'augustenborg-pizza',
    name: 'Augustenborg Pizza & Grill',
    street: 'Centervej 2',
    zip: '6440',
    address: 'Centervej 2, 6440 Augustenborg',
    city: 'Augustenborg',
    lat: 54.944,
    lng: 9.872,
    phone: '73702540',
    website: 'https://www.augustenborg-pizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'babaspizza',
    name: 'Babas Pizza & Grill i Esbjerg',
    street: '',
    zip: '1823',
    address: '1823 Forsiden',
    city: 'Forsiden',
    lat: 56.26,
    lng: 9.5,
    phone: '93921823',
    website: 'https://www.babaspizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'bambi-pizza',
    name: 'Bambi Pizza og Grill House Holstebro',
    street: 'Struervej 49',
    zip: '7500',
    address: 'Struervej 49, 7500 Holstebro',
    city: 'Holstebro',
    lat: 56.36,
    lng: 8.62,
    phone: '97425125',
    website: 'https://www.bambi-pizza.dk',
    hoursOpen: '12:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'bellaitalia',
    name: 'Bella Italia Pizza Esbjerg',
    street: 'Gl Vardevej 171',
    zip: '6715',
    address: 'Gl Vardevej 171, 6715 Esbjerg',
    city: 'Esbjerg',
    lat: 55.521,
    lng: 8.469,
    phone: '75459001',
    website: 'https://www.bellaitalia.dk',
    hoursOpen: '14:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'bellavodskov',
    name: 'Bella Italia Pizza og Grill I Vodskov',
    street: 'Vodskovvej 35',
    zip: '9310',
    address: 'Vodskovvej 35, 9310 Vodskov',
    city: 'Vodskov',
    lat: 57.109,
    lng: 10.022,
    phone: '52705877',
    website: 'https://www.bellavodskov.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'bigbite',
    name: 'Big Bite Pizza & Burger',
    street: 'Fyensgade 38',
    zip: '9000',
    address: 'Fyensgade 38, 9000 Aalborg',
    city: 'Aalborg',
    lat: 57.048,
    lng: 9.922,
    phone: '98102079',
    website: 'https://www.bigbite.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'bogeskovpizza',
    name: 'Bøgeskov Pizza og Steakhouse i Bøgeskov, Fredericia',
    street: 'Bøgeskovvej 41',
    zip: '7000',
    address: 'Bøgeskovvej 41, 7000 Fredericia',
    city: 'Fredericia',
    lat: 56.26,
    lng: 9.5,
    phone: '75727072',
    website: 'https://www.bogeskovpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'brammingpizza',
    name: 'Bramming Pizza og Kebabhouse',
    street: 'Nørregade 25',
    zip: '6740',
    address: 'Nørregade 25, 6740 Bramming',
    city: 'Bramming',
    lat: 55.469,
    lng: 8.703,
    phone: '75174700',
    website: 'https://www.brammingpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'broagerpizza',
    name: 'Broager Pizza I Broager',
    street: 'Storegade 23',
    zip: '6310',
    address: 'Storegade 23, 6310 Broager',
    city: 'Broager',
    lat: 54.891,
    lng: 9.672,
    phone: '73441312',
    website: 'https://www.broagerpizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'byenspizzaria',
    name: 'Byens Pizzaria',
    street: 'Nørregade 10',
    zip: '9700',
    address: 'Nørregade 10, 9700 Brønderslev',
    city: 'Brønderslev',
    lat: 56.26,
    lng: 9.5,
    phone: '98802024',
    website: 'https://www.byenspizzaria.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'cafealfa',
    name: 'Cafe Alfa Holstebro',
    street: 'Nørregade 48',
    zip: '7500',
    address: 'Nørregade 48, 7500 Holstebro',
    city: 'Holstebro',
    lat: 56.36,
    lng: 8.62,
    phone: '81864929',
    website: 'https://www.cafealfa.dk',
    hoursOpen: '11:00',
    hoursClose: '20:00',
    delivery: true,
    active: true
  },
  {
    id: 'cafeistanbul',
    name: 'Cafe Istanbul Pizza Haderslev',
    street: 'Apotekergade 2 st.',
    zip: '6100',
    address: 'Apotekergade 2 st., 6100 Haderslev',
    city: 'Haderslev',
    lat: 56.26,
    lng: 9.5,
    phone: '73531095',
    website: 'https://www.cafeistanbul.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'centrepalace',
    name: 'Centre Palace',
    street: '',
    zip: '2078',
    address: '2078 Forsiden',
    city: 'Forsiden',
    lat: 56.26,
    lng: 9.5,
    phone: '86102078',
    website: 'https://www.centrepalace.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'chaps-pizza',
    name: 'Chaps Pizza i Aabenraa',
    street: 'Vestergade 7A',
    zip: '6200',
    address: 'Vestergade 7A, 6200 Aabenraa',
    city: 'Aabenraa',
    lat: 55.044,
    lng: 9.418,
    phone: '73622200',
    website: 'https://www.chaps-pizza.dk',
    hoursOpen: '16:00',
    hoursClose: '20:45',
    delivery: true,
    active: true
  },
  {
    id: 'dannipizzaoggrill',
    name: 'Danni Pizza & Grill i Aarhus',
    street: 'J. P. Larsensvej 4',
    zip: '8220',
    address: 'J. P. Larsensvej 4, 8220 Brabrand',
    city: 'Brabrand',
    lat: 56.153,
    lng: 10.135,
    phone: '86614412',
    website: 'https://www.dannipizzaoggrill.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'davinciaulum',
    name: 'Da Vinci Aulum',
    street: 'Danmarksgade 3-5',
    zip: '7490',
    address: 'Danmarksgade 3-5, 7490 Aulum',
    city: 'Aulum',
    lat: 56.266,
    lng: 8.789,
    phone: '97427490',
    website: 'https://www.davinciaulum.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'dinospizza',
    name: 'Dinos Pizza & Restaurant i Struer',
    street: 'Østergade 34',
    zip: '7600',
    address: 'Østergade 34, 7600 Struer',
    city: 'Struer',
    lat: 56.484,
    lng: 8.594,
    phone: '97852525',
    website: 'https://www.dinospizza.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'dinosroslev',
    name: "Dino's Pizzaria i Roslev",
    street: 'Frederiksgade 17',
    zip: '7870',
    address: 'Frederiksgade 17, 7870 Roslev',
    city: 'Roslev',
    lat: 56.7,
    lng: 8.982,
    phone: '97591533',
    website: 'https://www.dinosroslev.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'doropizza',
    name: 'Doro Pizza Restaurant i Gråsten',
    street: '',
    zip: '6800',
    address: '6800 Forsiden',
    city: 'Forsiden',
    lat: 56.26,
    lng: 9.5,
    phone: '74654240',
    website: 'https://www.doropizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'emmapizza',
    name: 'Emma Pizza & Grill i Aarhus',
    street: 'Sønderborggade 9',
    zip: '8000',
    address: 'Sønderborggade 9, 8000 Aarhus',
    city: 'Aarhus',
    lat: 56.157,
    lng: 10.203,
    phone: '86144949',
    website: 'https://www.emmapizza.dk',
    hoursOpen: '15:30',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'falafelhouse',
    name: 'Falafel House i Aalborg',
    street: 'Reberbansgade 16 A',
    zip: '9000',
    address: 'Reberbansgade 16 A, 9000 Aalborg',
    city: 'Aalborg',
    lat: 57.048,
    lng: 9.922,
    phone: '32117311',
    website: 'https://www.falafelhouse.dk',
    hoursOpen: '11:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'fanoepizza',
    name: 'Fanø Pizza på Fanø',
    street: 'Valdemarsvej 14',
    zip: '6720',
    address: 'Valdemarsvej 14, 6720 Fanø',
    city: 'Fanø',
    lat: 55.416,
    lng: 8.407,
    phone: '75161122',
    website: 'https://www.fanoepizza.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'gedvedgrillen',
    name: 'Gedved Grillen i Gedved',
    street: 'Egebjergvej 21',
    zip: '8751',
    address: 'Egebjergvej 21, 8751 Gedved',
    city: 'Gedved',
    lat: 55.932,
    lng: 9.847,
    phone: '30113444',
    website: 'https://www.gedvedgrillen.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'goldenspizza',
    name: 'Goldens Pizza og Burger i Børkop',
    street: 'Ågade 1',
    zip: '7080',
    address: 'Ågade 1, 7080 Børkop',
    city: 'Børkop',
    lat: 56.26,
    lng: 9.5,
    phone: '75861555',
    website: 'https://www.goldenspizza.dk',
    hoursOpen: '12:00',
    hoursClose: '21:30',
    delivery: true,
    active: true
  },
  {
    id: 'gustoherning',
    name: 'Gusto Sandwich & Pizza Herning',
    street: 'Østergade 12',
    zip: '7400',
    address: 'Østergade 12, 7400 Herning',
    city: 'Herning',
    lat: 56.139,
    lng: 8.974,
    phone: '71662090',
    website: 'https://www.gustoherning.dk',
    hoursOpen: '15:00',
    hoursClose: '21:00',
    delivery: false,
    active: true
  },
  {
    id: 'pizza-mix',
    name: 'Velkommen til Pizza Mix i Aalborg! Vi tilbyder et stort',
    street: 'Danmarksgade 28',
    zip: '9000',
    address: 'Danmarksgade 28, 9000 Aalborg',
    city: 'Aalborg',
    lat: 57.048,
    lng: 9.922,
    phone: '98160316',
    website: 'https://www.pizza-mix.dk',
    hoursOpen: '16:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'r-pizza',
    name: 'Rønhaveplads Pizza & Grill Sønderborg. Byens bedste Tak',
    street: 'Rønhaveplads 7',
    zip: '6400',
    address: 'Rønhaveplads 7, 6400 Sønderborg',
    city: 'Sønderborg',
    lat: 54.909,
    lng: 9.792,
    phone: '74436446',
    website: 'https://www.r-pizza.dk',
    hoursOpen: '10:45',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'sakurasushibar',
    name: 'Sakura Sushi Bar i Horsens',
    street: 'Åboulevarden 73',
    zip: '8700',
    address: 'Åboulevarden 73, 8700 Horsens',
    city: 'Horsens',
    lat: 56.26,
    lng: 9.5,
    phone: '29792288',
    website: 'https://www.sakurasushibar.dk',
    hoursOpen: '14:00',
    hoursClose: '21:00',
    delivery: true,
    active: true
  },
  {
    id: 'skalborgpizza',
    name: 'Skalborg Pizza',
    street: 'Hobrovej 390',
    zip: '9200',
    address: 'Hobrovej 390, 9200 Aalborg SV',
    city: 'Aalborg SV',
    lat: 57.014,
    lng: 9.901,
    phone: '98182327',
    website: 'https://www.skalborgpizza.dk',
    hoursOpen: '16:00',
    hoursClose: '20:25',
    delivery: true,
    active: true
  }
  ,{
    id: 'hobropizza',
    name: 'Hobro Pizza & Grill',
    street: 'Adelgade 53',
    zip: '9500',
    address: 'Adelgade 53, 9500 Hobro',
    city: 'Hobro',
    lat: 56.643,
    lng: 9.790,
    phone: '29759500',
    website: 'https://www.hobropizza.dk',
    hoursOpen: '12:00',
    hoursClose: '20:45',
    delivery: true,
    active: true
  }
];
